GOLD GYM Final Version
Hidar37/gym-project pull request #1
Opened 2022-09-14 14:32 UTC by Hidar37

- Basic structure of the page added.
- feature section is added dynamically.
- index and about section is available for use.
- no linter problem exists.
- mobile first approach.
- I have added also desktop version.
- hamburger menu added to mobile version
- More button is working in index page for mobile version.
- website is create with best HTML,CSS and JS practice.
- Readme file added completely.
- **loom video link:** [https://www.loom.com/share/d53bec270150473394fbb1fe41e5213a](url).

2022-09-14 16:11 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @Hidar37, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - No linter errors. ✔️
 - Nice topic. ✔️ 
 - Great video presentation and nice piece of code you liked. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-14 16:11 UTC, leonardodiasb commented on source/style/style.css
> +}
- [x] Although the footer is not showing in the template mobile view of the home page, there should be a footer on both mobile pages. Please make the footer visible.

2022-09-14 16:11 UTC, leonardodiasb commented on source/style/style.css
> +  background-color: #dfdede;
- [x] Please try to follow the same color palette as the template. The background color of the footer on both pages of the mobile view should be white. On the desktop view, the home page footer has a white background color too, and the about page has a dark background color. Please use the colors provided in the color swatch.

2022-09-14 16:11 UTC, leonardodiasb commented on index.html
> +  </nav>
- [x] Your navbar looks very nice but it misses a top dark bar with the social media links, logout, and language. Please add that and follow the alignment, color, and size of the template.

2022-09-14 16:11 UTC, leonardodiasb commented on index.html
> +    </div>
- [x] Your cards look great, but there is a minor difference from this section to the template. Please follow the template and add 5 cards to this section.
 - [OPTIONAL] These cards behave like a list so maybe using an `<ul>` to group them would make the HTML code make more sense.

2022-09-14 16:11 UTC, leonardodiasb commented on index.html
> +    </div>
- [x] The section of 'Featured Speakers' should be generated dynamically with JS. This means that the HTML code should be generated through Javascript, not only the text content of them. The purpose of this is that you can add new cards by adding an extra object in the data array you use to populate it. In your case, you cannot add only the data in the javascript because the amount of cards you created in this HTML file doesn't match with the number of cards in the data array of your javascript. Please remove the unnecessary HTML code of the feature speakers section and make it be created dynamically with Javascript.
 - [x] The design of the cards mismatch a lot from the template provided and they don't look consistent. The cards should have an image, title, subtitle, and description. Each article has two columns, the first with the image at the left and the second with the title, subtitle, and description.
 - [x] Kindly add 6 featured speakers to this section as there are in the template.
 -Your design: 
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/61919617/190203136-ab37ed85-3ebd-4f1a-aa2d-7e07ba79a250.png">

 -Template design:
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/61919617/190203181-55560ac7-da76-4e7f-8fda-d27dbc0e9a74.png">

2022-09-14 16:11 UTC, leonardodiasb commented on source/js/feature-speaker.js
> +}
- [x] As mentioned previously, the 'Featured Speakers' section should be created dynamically with Javascript. The Javascript code should create the HTML content, not only add text to it. Please refactor that code in order to create that section.

2022-09-14 16:11 UTC, leonardodiasb commented on about-us.html
> +    <h1 class="p-header">Partner</h1>
- [ ] There should be no more than 1 `<h1>` tag on a page. Please take a look at [this article](https://www.contentkingapp.com/academy/headings/) about the headings and fix this issue.

2022-09-14 16:11 UTC, leonardodiasb commented on index.html
> +    <h1 class="services-header">Main Services</h1>
- [ ] There should be no more than 1 `<h1>` tag on a page. Please take a look at [this article](https://www.contentkingapp.com/academy/headings/) about the headings and fix this issue.

2022-09-14 16:11 UTC, leonardodiasb commented on index.html
> +    <h1 class="services-header speaker-header">Clients Feedback</h1>
- [ ] There should be no more than 1 `<h1>` tag on a page. Please take a look at [this article](https://www.contentkingapp.com/academy/headings/) about the headings and fix this issue.

2022-09-14 16:11 UTC, leonardodiasb commented on index.html
> +    <h1 class="p-header">Partner</h1>
- [ ] There should be no more than 1 `<h1>` tag on a page. Please take a look at [this article](https://www.contentkingapp.com/academy/headings/) about the headings and fix this issue.

2022-09-15 12:28 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @Hidar37 :wave:

## Highlights :1st_place_medal:

:heavy_check_mark: Following GitHub Flow
:heavy_check_mark: Descriptive PR Title
:heavy_check_mark: Descriptive PR Summary

Good job on implementing some of the requested changes, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-15 12:28 UTC, HAMMAS-SALEEM commented on source/js/feature-speaker.js
> +}
### Your Speaker Card
![Screenshot from 2022-09-15 17-17-14 (copy)](https://user-images.githubusercontent.com/93039359/190402928-a45d8b06-22d9-48d5-ae22-d5b9ab7a6c33.png)

### Behance Speaker Card
![Screenshot from 2022-09-15 17-18-47 (another copy)](https://user-images.githubusercontent.com/93039359/190402947-891a40ee-507a-471e-9f53-6fff0a2fd7a3.png)

- [ ] You are missing the black n white box background in each card of speaker. Please add it to make your desing look professinal and similar to the Behance's design as requested by the previous reviewer :blush:

2022-09-15 12:28 UTC, HAMMAS-SALEEM commented on README.md
> +## Built With
**[Optional]**
- [ ] Please add an 5 mins introductory loom video of your project. This is your documentation file so it should contain an intro video of your application. :+1:

2022-09-15 12:38 UTC, Hidar37 commented on source/js/feature-speaker.js
> +}
**@HAMMAS-SALEEM** 
hello dear sir thanks a lot for your feedback.
can you give me any idea on how to add that **black and white background** to images that you have said thanks a lot.

2022-09-15 12:40 UTC, HAMMAS-SALEEM commented on source/js/feature-speaker.js
> +}
@Hidar37 Yeah sure. You can use position absolute in this case for your speaker image so it would become moveable. You also need to use z-index to make your speaker image to come before the black and white background :thinking:

You can reach out to me on slack if you didn't get this. We can solve this in one call :+1:

2022-09-16 18:46 UTC, jasonfelice requested changes
Hi  @Hidar37, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Suggested changes
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-09-16 18:46 UTC, jasonfelice commented on index.html
> +  <section class="services feature-speaker">
- [ ] Please make sure that the speakers are perfectly in the center. Currently, they are a little bit towards the left.

![image](https://user-images.githubusercontent.com/92215878/190708279-cec23d7d-234b-49b1-8b38-1f6b57dac2e7.png)

2022-09-16 18:46 UTC, jasonfelice commented on source/style/style.css
> +.feature-card {
- [ ] Kindly add a gap between the text and the image so it looks more like the given design. 😄 

![image](https://user-images.githubusercontent.com/92215878/190708609-13d05306-8e6d-4335-974b-283b7a1bdce4.png)

2022-09-16 18:46 UTC, jasonfelice commented on source/style/style.css
> +}
- [ ] Kindly use `background-color: #414246`. This looks more like the given design.
- [ ] [Optional] You can make this section look better by adding some padding.

![image](https://user-images.githubusercontent.com/92215878/190709212-0f239a13-89b9-4f95-8454-d15f860686f9.png)

2022-09-16 19:49 UTC, frank1738 approved these changes
Hi @Hidar37 , 

Good work implementing the changes requested. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![YesYouAreGIF (2)](https://user-images.githubusercontent.com/50941074/172881298-64e98170-87c5-4075-8a77-71d65d991f55.gif)


## Highlights

✅ No linter error
✅ README is okay
✅ Good Design 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 19:53 UTC, merged